CXX = g++             
CXXFLAGS = -Wall -g    
# Below are the List of source files
SRCS =  Main.cpp conga_raj.cpp zombie_raj.cpp EC.cpp
# Below are the List of object files generated by replacing .cpp with .o
OBJS = $(SRCS:.cpp=.o)
# Below are the Header file mentioned
HEADERS = linkedlist_raj.hpp zombie_raj.h conga_raj.h EC.h
# Below is the name of the executable mentioned
TARGET = exe

# Below is used for building the target executable
$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $(OBJS)

# Below is used for building object files from corresponding source files
%.o: %.cpp $(HEADERS)
	$(CXX) $(CXXFLAGS) -c $<

# Below is used to clean to remove object files and the target executables
clean:
	rm -f $(OBJS) $(TARGET) $(EXE)



